### ISSUE TITLE
What the licences of this project? 

### ISSUE THREAD

**Issue by igreenfield** [krishna81m/jackson-nested-prop-filter#1]

**Comment by krishna81m** [comment]
Hi there, I have no clue about licensing. This project was really just "an idea" for someone on stackoverflow. I am unable to get time to clean it up, verify or write tests. So, feel free to use, modify and make changes.

**Comment by igreenfield** [comment]
Can i use it in commercial use case?

**Comment by krishna81m** [comment]
:+1:, don't forget to test before you use it, let me clean it up a little bit soon.

**Comment by igreenfield** [comment]
What do you think of adding https://www.apache.org/licenses/LICENSE-2.0 to the repo?

**Comment by krishna81m** [comment]
Sounds like a good idea, thanks.

**Comment by igreenfield** [comment]
I will add

**Comment by igreenfield** [comment]
Add. please approve the pull request.

**Comment by krishna81m** [comment]
I see everything approved and merged.
